import { query } from './database.js';

// VendPOS schema migration. Mirrors backend/database/schema.sql.
// On a fresh DB this is the authoritative install script. On a DB
// holding the prototype schema (stores/inventory/sales), the leading
// DROP block clears it before the new tables are created. Issue #1.
const migrations = [
  // Drop legacy prototype tables (idempotent — safe on a fresh DB).
  `DROP TABLE IF EXISTS sale_items CASCADE`,
  `DROP TABLE IF EXISTS sales CASCADE`,
  `DROP TABLE IF EXISTS inventory CASCADE`,
  // products/users/stores are recreated below; drop in dependency order.
  `DROP TABLE IF EXISTS transaction_items CASCADE`,
  `DROP TABLE IF EXISTS transactions CASCADE`,
  `DROP TABLE IF EXISTS products CASCADE`,
  `DROP TABLE IF EXISTS users CASCADE`,
  `DROP TABLE IF EXISTS stores CASCADE`,
  `DROP TABLE IF EXISTS tenants CASCADE`,

  // 1. tenants
  `CREATE TABLE tenants (
    tenant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(150) NOT NULL,
    subscription_tier VARCHAR(50) NOT NULL DEFAULT 'Starter',
    logo_url VARCHAR(500),
    theme_color VARCHAR(7) DEFAULT '#3B82F6',
    address TEXT,
    phone VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )`,

  // 2. users
  `CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'Cashier' CHECK (role IN ('Owner', 'Cashier')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )`,

  // 3. products (stock lives here)
  `CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(70) NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    cost NUMERIC(12, 2),
    current_stock INT NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    reorder_level INT NOT NULL DEFAULT 10 CHECK (reorder_level >= 0),
    sku VARCHAR(100),
    image_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )`,

  // 4. transactions (append-only — see ADR-0001)
  `CREATE TABLE transactions (
    transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )`,

  // 5. transaction_items
  `CREATE TABLE transaction_items (
    transaction_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0)
  )`,

  // Indexes per ERD
  `CREATE INDEX idx_users_tenant ON users(tenant_id)`,
  `CREATE INDEX idx_products_tenant ON products(tenant_id)`,
  `CREATE INDEX idx_transactions_tenant ON transactions(tenant_id)`,
  `CREATE INDEX idx_items_transaction ON transaction_items(transaction_id)`,
  `CREATE INDEX idx_products_tenant_search ON products(tenant_id, category, name)`,

  // Perf extensions
  `CREATE INDEX idx_users_email ON users(email)`,
  `CREATE INDEX idx_transactions_created_at ON transactions(created_at)`,
  `CREATE UNIQUE INDEX idx_products_tenant_sku ON products(tenant_id, sku) WHERE sku IS NOT NULL`,

  // updated_at trigger
  `CREATE OR REPLACE FUNCTION update_updated_at_column()
   RETURNS TRIGGER AS $$
   BEGIN
      NEW.updated_at = CURRENT_TIMESTAMP;
      RETURN NEW;
   END;
   $$ language 'plpgsql'`,

  `CREATE TRIGGER update_tenants_updated_at BEFORE UPDATE ON tenants
   FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()`,
  `CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
   FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()`,
  `CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
   FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()`
];

async function runMigrations() {
  console.log('🚀 Starting VendPOS database migration...\n');

  try {
    for (let i = 0; i < migrations.length; i++) {
      console.log(`Running migration ${i + 1}/${migrations.length}...`);
      await query(migrations[i]);
    }

    console.log('\n✅ Migration complete.');
    console.log('\n📊 Schema:');
    console.log('   • tenants');
    console.log('   • users');
    console.log('   • products');
    console.log('   • transactions');
    console.log('   • transaction_items\n');

    process.exit(0);
  } catch (error) {
    console.error('\n❌ Migration failed:', error.message);
    console.error(error);
    process.exit(1);
  }
}

import { fileURLToPath } from 'url';
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  runMigrations();
}

export default runMigrations;
